### ISSUE TITLE
image width and height attributes

### ISSUE THREAD

**Issue by cspanring** [davidbilling/ember-cli-cloudinary-light#1]
If I set `crop= "limit"`, the image `width` and `height` attributes will skew the image. Are you open to have them optional? Happy to submit a PR if that's OK.

**Comment by davidbilling** [comment]
@cspanring It should be optional to cloudinary, you mean the attributes set? Does setting width to auto fix it? Yes, please submit a PR, Thanx!

**Comment by cspanring** [comment]
The `width/height` attribute on the `img` tag should be optional. I can't use crop=limit in combination with a fixed height/width on the image tag, as cloudinary will make the decision about the final image dimensions. Cloudinary needs the width/height for its crop-limit option.

**Comment by davidbilling** [comment]
@cspanring AttributeBindings will not render if null, so maybe I should just set them default to null if no value is given? Do you think that will work?

**Comment by davidbilling** [comment]
@cspanring Can you verify if the latest version fix this problem?

**Comment by cspanring** [comment]
@davidbilling yes, thanks, that works!

**Comment by davidbilling** [comment]
@cspanring Great! =)
