### ISSUE TITLE
Deprecated and removed htmlSafe in @ember/string

### ISSUE THREAD

**Issue by JohannKa** [davidbilling/ember-cli-cloudinary-light#74]
Hello there
Thanks for your work !

Migrating from Ember 3.28 to 4.9 I encountered a major issue : htmlSafe was deprecated in @ember/string since 3.25 and is now moved to @ember/template in 4.x making ember-cli-cloudinary-light unusable :

[https://deprecations.emberjs.com/ember/v3.x/#toc_ember-string-htmlsafe-ishtmlsafe](https://deprecations.emberjs.com/ember/v3.x/#toc_ember-string-htmlsafe-ishtmlsafe)

**Comment by davidbilling** [comment]
Thanks @JohannKa!  I created a new release with your fix.
